[project]
name = "ecg-federatedlearning"
version = "0.1.0"
description = "Federated Learning with Flower.ai"
dependencies = [
    "flwr[simulation]>=1.13.0",
    "torch==2.4.1",
    "wfdb>=3.4.1",
    "pandas>=2.2.0",
    "scikit-learn>=1.5.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

#To exclude data-folder and connect flower to the code-files in the data folder
[tool.setuptools.packages.find]
where = ["."]                 
include = ["ecg_code*"] 
exclude = ["data*", "flwr-ecg-env*"]          

[tool.flwr.app]
publisher = "danie"

[tool.flwr.app.components]
serverapp = "ecg_code.federated_training.server_app:app"
clientapp = "ecg_code.federated_training.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3
batch-size = 32
local-epochs = 1
learning-rate = 0.01
num-partitions = 2

[tool.flwr.federations.local-simulation]
options.num-supernodes = 2
